### ISSUE TITLE
speakout plugin - limite para entrada de emails

### ISSUE THREAD

**Issue by kannonsan** [piratas/piratas-site#3]
este plugin para petições está instalado no servidor

entretanto ele foi instalado com limites para o campo de emails, um limite de 300 caracteres
por mais que façamos a mudança pelo administrador do WordPress, o DB continua com 300

assim diz instalador dele:

$sql_create_tables = "
		CREATE TABLE `$db_petitions` (
			
			`target_email` **VARCHAR(300)** CHARACTER SET utf8 NOT NULL,

Desta forma, com o limite de 300 caracteres, não conseguimos inserir os emails de todos deputados.
Precisamos modificar esse limite.

**Comment by iuriguilherme** [comment]
Como dito em https://github.com/piratas/gti/issues/47

Se o instalador permite criar o banco de dados, então a primeira coisa a se fazer é reinstalar o plugin

Aonde está o código fonte do plugin?

**Comment by kannonsan** [comment]
O plugin, já com modificações como tradução, está instalado no site.
Pode-se pegar no diretório, corrigir no instalador, zipa-lo, e reinstalar pelo painel do WP.

Existem mil e uma maneiras de fazer Neston. Mas eu não tenho Neston. 

Pode-se tbm abandonar o uso do plugin e instalar essa plataforma https://github.com/piratas/gti/issues/46 ou como sugestão que me deram hoje, fazer tudo pelo Avaaz.

O que seria uma pena pois é na verdade uma outra coisa, n tem nada com Avaaz.

**Comment by dseeker** [comment]
@kannonsan mas ocorreu erro por causa deste limite? quantas vezes um email extrapola 300 chars? ou voce quer enviar para varios ao mesmo tempo? voce tem que tomar cuidado para evitar praticas que vao fazer esses emails ficarem no spam folder das pessoas

**Comment by kannonsan** [comment]
> @kannonsan mas ocorreu erro por causa deste limite? quantas vezes um email extrapola 300 chars? ou voce quer enviar para varios ao mesmo tempo? voce tem que tomar cuidado para evitar praticas que vao fazer esses emails ficarem no spam folder das pessoas

Sim, é um "spam" para todos congressistas.

**Comment by dseeker** [comment]
dentro do phpMyAdmin é possivel mudar o campo diretamente
entra na tabela q vc quer mudar, va em estrutura e clique "change" no campo. modifique para "text" como neste print
![image](https://cloud.githubusercontent.com/assets/11655138/20744421/3cb16fc2-b6dc-11e6-987f-9519530408d0.png)

**Comment by iuriguilherme** [comment]
@dseeker não tem php admin, eu faço a alteração na tabela com o cliente oficial do mysql.

Isto eu sei fazer, a questão é que isto não deve ser feito no site em produção. Já tiramos o site do ar mais de uma vez por ficar testando plugins e alterando o banco de dados, e isto não vai mais acontecer.

O fluxo proposto é identificar a necessidade, escolher a ferramenta (no caso o plugin), trazer a ferramenta pro ambiente de desenvolvimento (no caso o código fonte desse plugin, a árvore git, o arquivo compactado instalável ou no mínimo o link), testa, homologa, e bota em produção. Que nem todo mundo faz há séculos e funciona.

No nosso caso aqui, ninguém ainda sabe nem o nome do plugin.

**Comment by kannonsan** [comment]
O problema seria facilmente resolvido como notou @dseeker e anteriormente (no caso da CPICiber em que fizemos) foi resolvido desta forma: mudando diretamente no banco de dados.

Entretanto, não vejo mais isso como uma questão. 

Apesar da votação no Loomio, a lentidão em resolver problemas fáceis como esse criam uma barreira intransponível para tornamos ações como essa uma rotina no Partido Pirata. 

Os textos são preparados coletivamente. Imagens, vídeos, gifs. Levado a reunião Votado no Loomio. Tudo pronto e quando chega na hora... veja só. Se fosse algo urgente, como seria?

Para mim é óbvio: é preciso que quem administre as ferramentas sejam pessoas que igualmente as usem! Só isso.

Eu estarei alugando com meu próprio dinheiro um servidor para poder instalar ferramentas e assim apresenta-las em deliberações. E sugiro que outros piratas façam o mesmo.

PS: o plugin já foi atualizado, traduzido e agora funciona de forma plena.

**Comment by dseeker** [comment]
@desci o processo seria clonar a tabela, alterar a configuracoes na tabela clonada, mudar as configuracoes no staging enviroment para apontar o site para essa essa tabela, e se estiver verificado funcionando, alterar a configuracao do server de producao para a tabela clonada.
